version: "2"

services:
  sonerezh:
    image: sonerezh
    hostname: sonerezh
    container_name: music
    volumes:
      - /data/sonerezh/thumbnails:/thumbnails
      - /home/seuf/Music:/music
    expose:
      - 80
    ports:
      - "8181:80"
    environment:
      DB_ENV_HOST: 'db_sonerezh:3306'
      DB_ENV_MYSQL_DATABASE: 'sonerezh'
      DB_ENV_MYSQL_USER: 'sonerezh'
      DB_ENV_MYSQL_PASSWORD: 'Sonerezh_user_password_here'

  db_sonerezh:
    image: mariadb:10
    hostname: db_sonerezh
    container_name: db_sonerezh
    volumes:
      - /data/sonerezh/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password_here'
      MYSQL_DATABASE: 'sonerezh'
      MYSQL_USER: 'sonerezh'
      MYSQL_PASSWORD: 'Sonerezh_user_password_here'
    expose:
      - 3306

